Adjustments

diff --git a/.github/workflows/coverity.yml b/.github/workflows/coverity.yml
--- a/.github/workflows/coverity.yml
+++ b/.github/workflows/coverity.yml
@@ -54,11 +54,14 @@ jobs:
             --data "token=${{secrets.COVERITY_TOKEN}}&project=${{env.COVERITY_PROJECT}}" || { echo "Download failed"; exit 1; }
           mkdir cov-linux64-tool
           tar -xzf cov-linux64-tool.tar.gz --strip 1 -C cov-linux64-tool
-
-      # - name: Download Intel® oneAPI Base Toolkit
-      #   run: |
-      #     wget --progress=dot:giga https://registrationcenter-download.intel.com/akdlm/IRC_NAS/6caa93ca-e10a-4cc5-b210-68f385feea9e/intel-oneapi-base-toolkit-2025.3.1.36_offline.sh
-      #     sudo bash intel-oneapi-base-toolkit-2025.3.1.36_offline.sh -s -a -s --action install --eula accept
+          cd cov-linux64-tool/config
+          git apply --check ${GITHUB_WORKSPACE}/.github/workflows/fix.coverity-2024.12.patch
+          if patch -p1 < ${GITHUB_WORKSPACE}/.github/workflows/fix.coverity-2024.12.patch; then
+            echo "Coverity Build Tool configs successfully patched"
+          else
+            echo "Coverity Build Tool configs patching failed, check patch relevance to current Coverity Build Tool version"
+            exit 1
+          fi
 
       - name: Download Intel compiler
         run: |
@@ -77,15 +80,17 @@ jobs:
           export PATH="${PWD}/cov-linux64-tool/bin:${PATH}"
           cov-configure --template --compiler icpx --comptype intel_icpx:linux
           ls -la
+
+          shopt -s nullglob
+          GLOBIGNORE="american_options:batched_linear_solver:cov-int:*git*"
+
           for d in */; do
-            [[ "$d" == *git* || "$d" == *cov-int* ]] && continue
             echo ">> $d"
             (cd "$d" && cov-build --dir ../cov-int --append-log --delete-stale-tus make || [[ $? -eq 2 ]])
           done
 
       - name: Archive oneMKL-samples build results
         run: |
-          tar -czf build.tgz .
           tar -czf cov-int.tgz cov-int
           size=$(du -m cov-int.tgz | cut -f1)
           echo "Artifact size: $size MB"
@@ -94,8 +99,8 @@ jobs:
       - name: Cache build archive
         uses: actions/cache@v4
         with:
-          path: build.tgz
-          key: oneMKL-samples-cov-build-${{github.sha}}
+          path: cov-int.tgz
+          key: oneMKL-samples-cov-dir-${{github.sha}}
 
       # - name: Submit Coverity results for analysis
       #   run: |
