Adjustments

diff --git a/.github/workflows/coverity.yml b/.github/workflows/coverity.yml
--- a/.github/workflows/coverity.yml
+++ b/.github/workflows/coverity.yml
@@ -96,25 +96,25 @@ jobs:
           echo "Artifact size: $size MB"
           echo "size=$size" >> $GITHUB_OUTPUT
 
-      # - name: Submit Coverity results for analysis
-      #   run: |
-      #     cd build
-      #     curl -X POST \
-      #       -d version="${GITHUB_SHA}" \
-      #       -d description="" \
-      #       -d email="${{secrets.COVERITY_EMAIL}}" \
-      #       -d token="${{secrets.COVERITY_TOKEN}}" \
-      #       -d file_name=@cov-int.tgz \
-      #       https://scan.coverity.com/projects/${{env.COVERITY_PROJECT_ID}}/builds/init \
-      #       | tee response
-      #     upload_url=$(jq -r '.url' response)
-      #     if [ -z "$upload_url" ] || [ "$upload_url" == "null" ]; then
-      #       echo "Error: Failed to extract 'url' from API response." >&2
-      #       cat response >&2
-      #       exit 1
-      #     fi
-      #     build_id=$(jq -r '.build_id' response)
-      #     curl -X PUT \
-      #       --header 'Content-Type: application/json' \
-      #       --upload-file cov-int.tgz \
-      #       $upload_url
+      - name: Submit Coverity results for analysis
+        run: |
+          cd build
+          curl -X POST \
+            -d version="${GITHUB_SHA}" \
+            -d description="" \
+            -d email="${{secrets.COVERITY_EMAIL}}" \
+            -d token="${{secrets.COVERITY_TOKEN}}" \
+            -d file_name=@cov-int.tgz \
+            https://scan.coverity.com/projects/${{env.COVERITY_PROJECT_ID}}/builds/init \
+            | tee response
+          upload_url=$(jq -r '.url' response)
+          if [ -z "$upload_url" ] || [ "$upload_url" == "null" ]; then
+            echo "Error: Failed to extract 'url' from API response." >&2
+            cat response >&2
+            exit 1
+          fi
+          build_id=$(jq -r '.build_id' response)
+          curl -X PUT \
+            --header 'Content-Type: application/json' \
+            --upload-file cov-int.tgz \
+            $upload_url
